# Generated by Django 4.2.7 on 2023-11-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.IntegerField()),
                ("day_of_week", models.IntegerField()),
                ("start_time_local", models.TimeField()),
                ("end_time_local", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="StoreReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.IntegerField()),
                ("uptime_last_hour", models.IntegerField()),
                ("uptime_last_day", models.FloatField()),
                ("uptime_last_week", models.FloatField()),
                ("downtime_last_hour", models.IntegerField()),
                ("downtime_last_day", models.FloatField()),
                ("downtime_last_week", models.FloatField()),
                ("timestamp_utc", models.DateTimeField(auto_now_add=True)),
                ("report_id", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StoreStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.IntegerField()),
                ("timestamp_utc", models.DateTimeField()),
                ("status", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="StoreTimezone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.IntegerField()),
                ("timezone_str", models.CharField(max_length=50)),
            ],
        ),
    ]
