# Generated by Django 4.2.7 on 2023-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_monitor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storereport",
            name="timestamp_utc",
        ),
        migrations.AlterField(
            model_name="storereport",
            name="downtime_last_hour",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="storereport",
            name="report_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="storereport",
            name="uptime_last_hour",
            field=models.FloatField(),
        ),
    ]
