# Generated by Django 4.2.7 on 2023-11-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_monitor", "0004_remove_storereport_downtime_last_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storereport",
            name="data",
            field=models.JSONField(default=list),
        ),
    ]
